---
- name: Install epel-release
  yum: name=epel-release state=present

- name: Install Iptables
  yum: name=iptables state=present

- name: Install Iptables-services
  yum: name=iptables-services state=present

- name: Setup Iptables rules
  template: src=iptables dest=/etc/sysconfig/iptables
  notify: restart iptables

- name: Start Iptables
  service: name=iptables state=started enabled=yes

- name: Stop Firewalld
  service: name=firewalld state=stopped enabled=no

- name: Generate /etc/hosts file
  template:
    src=hosts
    dest=/etc/hosts
